[package]
name = "voproof"
version = "0.1.0"
edition = "2018"
description = "The rust implementation of the VOProof zkSNARK."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
