from sympy import Symbol, latex, sympify, Integer, simplify
from os.path import basename
from sympy.abc import alpha, beta, gamma, X, D, S
from optimized_compiler import VOProtocol, PIOPExecution, PIOPFromVOProtocol, \
                               ZKSNARKFromPIOPExecKZG, VOProtocolExecution
from vector_symbol import get_named_vector, reset_name_counters, get_name
from smvp_protocols import SparseMVP, SparseMVPProverEfficient, \
                           R1CS, R1CSProverEfficient, \
                           HPR, HPRProverEfficient
from pov_protocols import POV, POVProverEfficient

ell = Symbol("\\ell", positive=True)
m = Symbol("m", positive=True)
# n = Symbol("n", positive=True)
H = Symbol("H", positive=True)
K = Symbol("K", positive=True)
s = Symbol("s", positive=True)

Cc = Symbol("C_c", positive=True)
Ca = Symbol("C_a", positive=True)
Cm = Symbol("C_m", positive=True)
k = Symbol("k", positive=True)

def dump_performance(piopexec, zkSNARK, name):
  voexec = piopexec.reference_to_voexec
  print("%s preprocessed polynomials: %d" % (name, len(piopexec.indexer_polynomials)))
  print("%s online polynomials: %d" % (name, len(piopexec.prover_polynomials)))
  n_distinct = len(piopexec.distinct_points)
  print("%s distinct points: %d" % (name, n_distinct))
  n_evals = len(piopexec.eval_queries) + len(piopexec.eval_checks)
  print("%s eval queries: %d" % (name, n_evals))
  print("%s max degree: %s" % (name, latex(piopexec.max_degree)))
  print("%s minimal n: %s" % (name, latex(voexec.vector_size_bound)))
  n_field_elements = len([p for p in zkSNARK.proof if latex(p).startswith("y")])
  print("%s proof size: %d G + %d F" %
        (name, len(zkSNARK.proof) - n_field_elements, n_field_elements))
  c_g_exps = sum([len(poly_combine.coeff_latex_builders)
                 for poly_combine in piopexec.poly_combines])
  v_g_exps = n_evals + 2 * n_distinct - 2 + c_g_exps
  print("%s verifier G-exps: %d" % (name, v_g_exps))
  p_g_exps = c_g_exps + piopexec.max_degree * 4 + voexec.vector_size_sum
  print("%s prover G-exps: %s" % (name, latex(p_g_exps)))
  print()


def get_minimal_vector_size(protocol, ppargs, execargs, simplify_hints):
  voexec = VOProtocolExecution(Symbol("N"))
  voexec._simplify_max_hints = simplify_hints
  protocol.preprocess(voexec, *ppargs)
  protocol.execute(voexec, *execargs)
  reset_name_counters()
  return voexec.vector_size_bound

def analyzeProtocol(protocol, ppargs, execargs, simplify_hints, filename=None):
  name = protocol.__class__.__name__
  n = get_minimal_vector_size(protocol, ppargs, execargs, simplify_hints)
  debug("Start analyzing %s..." % name)
  piop = PIOPFromVOProtocol(protocol, n, D)
  piop.debug_mode = debug_mode
  debug("Start preprocessing...")
  piopexec = PIOPExecution()
  piop.preprocess(piopexec, *ppargs)
  piopexec.reference_to_voexec._simplify_max_hints = simplify_hints
  debug("Start executing...")
  piop.execute(piopexec, *execargs)
  piopexec.max_degree = piopexec.reference_to_voexec.simplify_max(piopexec.max_degree)

  debug("Start compiling to zkSNARK...")
  zkSNARK = ZKSNARKFromPIOPExecKZG(piopexec)
  debug()
  dump_performance(piopexec, zkSNARK, name)

  if filename is not None:
    with open("../%s.tex" % filename, "w") as f:
      print("%%%% This file is generated by scripts/%s"
            % basename(__file__), file=f)
      # print("\\subsubsection{Indexer.}", file=f)
      print(zkSNARK.dump_indexer(), file=f)
      print(file=f)
      print("\\subsubsection{Prover.}", file=f)
      print(zkSNARK.dump_prover(), file=f)
      print(file=f)
      print("\\subsubsection{Verifier.}", file=f)
      print(zkSNARK.dump_verifier(), file=f)

  reset_name_counters()


def analyzeR1CS():
  hints = [(S, H + 1), (S, K + 1), (H, K)]
  x = get_named_vector("x")
  x.local_evaluate = True
  ppargs = (H, K, S*3)
  execargs = (x, get_named_vector("w"), ell)
  analyzeProtocol(R1CS(), ppargs, execargs, hints, filename="compiled_r1cs")

def analyzeR1CSProverEfficient():
  hints = [(S, H + 1), (S, K + 1), (H, K)]
  x = get_named_vector("x")
  x.local_evaluate = True
  ppargs = (H, K, S*3)
  execargs = (x, get_named_vector("w"), ell)
  analyzeProtocol(R1CSProverEfficient(), ppargs, execargs, hints)

def analyzeHPR():
  Sp = Symbol(get_name("S'"), positive=True)
  hints = [(S, H + 1), (S, K + 1), (H, Sp), (K, ell), (H, ell), (S, ell + 1)]
  x = get_named_vector("x")
  x.local_evaluate = True
  ppargs = (H, K, S*3+Sp)
  execargs = (x, get_named_vector("w"), get_named_vector("w"), get_named_vector("w"), ell)
  analyzeProtocol(HPR(), ppargs, execargs, hints, filename="compiled_hpr")

def analyzeHPRProverEfficient():
  Sp = Symbol(get_name("S'"), positive=True)
  hints = [(S, H + 1), (S, K + 1), (H, Sp), (K, ell), (H, ell), (S, ell + 1), (H, K)]
  x = get_named_vector("x")
  x.local_evaluate = True
  ppargs = (H, K, S*3+Sp)
  execargs = (x, get_named_vector("w"), get_named_vector("w"), get_named_vector("w"), ell)
  analyzeProtocol(HPRProverEfficient(), ppargs, execargs, hints)

def analyzePOV():
  C = Symbol(get_name("C"), positive=True)
  hints = [(C, Ca + Cm + 1), (C, 1), (Ca, 1), (Cm, 1)]
  x = get_named_vector("x")
  x.local_evaluate = True
  ppargs = (get_named_vector("d"), C - Ca - Cm, Ca, Cm)
  execargs = (x, get_named_vector("a"), get_named_vector("b"), get_named_vector("c"))
  analyzeProtocol(POV(), ppargs, execargs, hints, filename="compiled_pov")

def analyzePOVProverEfficient():
  C = Symbol(get_name("C"), positive=True)
  hints = [(C, Ca + Cm + 1), (C, 1), (Ca, 1), (Cm, 1)]
  x = get_named_vector("x")
  x.local_evaluate = True
  ppargs = (get_named_vector("d"), C - Ca - Cm, Ca, Cm)
  execargs = (x, get_named_vector("a"), get_named_vector("b"), get_named_vector("c"))
  analyzeProtocol(POVProverEfficient(), ppargs, execargs, hints, filename="compiled_pov")

debug_mode = False

def debug(info=""):
  if debug_mode:
    print(info)

if __name__ == '__main__':
  # analyzeR1CSProverEfficient()
  # analyzeHPRProverEfficient()
  # analyzePOVProverEfficient()
  analyzeR1CS()
  analyzeHPR()
  analyzePOV()

